### ISSUE TITLE
Offline mode does not work properly

### ISSUE THREAD

**Issue by snsb-agrunz** [SNSB/DiversityNaviKey#1]
Also the selected db is cached in the IndexedDB, the cached data is not loaded when the internet connection was lost. 

## Console.log

`error in getDataOnline():  Error: Network Error `  
..  
` Error when trying to get rest version info TypeError: _context9.t1.response is undefined `  
..  
error in getDataOnline() is thrown without trying getDataOffline() ??

**Comment by snsb-agrunz** [comment]
error in getDataOnline() is thrown without trying getDataOffline() ??

**Comment by snsb-agrunz** [comment]
![Image](https://github.com/SNSB/DiversityNaviKey/assets/67312454/df6953a4-5395-42e5-b126-e510206eb7df)

**Comment by snsb-seifert** [comment]
In the REST API CORS is enabled for all endpoints throug flask_cors:
```

from flask_cors import CORS
...
app = Flask(__name__)
app.logger.setLevel(10)
CORS(app)
```

Can you check the cors-header?
"Access-Control-Allow-Origin: *"

```
curl 'https://divnavikey.snsb.info/data/' -H 'Accept: application/json'  -H 'Accept-Encoding: gzip, deflate, br' 

Header:
HTTP/1.1 200 OK
Date: Fri, 05 Apr 2024 06:55:11 GMT
Server: Apache/2.4.37 (CentOS Stream) OpenSSL/1.1.1k
Content-Type: application/json
Content-Length: 51
Access-Control-Allow-Origin: *
X-Forwarded-Prefix: /
Keep-Alive: timeout=5, max=98
Connection: Keep-Alive

{"data":["Ethnomyc","GFBio","BayernFlora","LIAS"]}

```
CORS header are sent.
